config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Default
  root to: "tasks#index"

  resources :tasks do
    resources :sub_tasks
  end
  
  post '/tasks/:id/sub_tasks' => 'sub_tasks#create', as: :create_sub_task
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :sub_tasks, class_name: "Task", foreign_key: "parent_task_id"
  belongs_to :parent_task, class_name: "Task"
  validates :task_name, :user_id, presence: true

  def private_task?
    self.task_type == true
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tasks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception  
end

app/controllers/sub_tasks_controller.rb
class SubTasksController < ApplicationController
  before_action :authenticate_user!, :set_task

  def create
    @sub_task = @task.sub_tasks.new(sub_task_params)
    @sub_task.user_id = current_user.id
    @sub_task.task_type = @task.task_type
    @sub_task.save
  end

  private
    def set_task
      @task = Task.find(params[:task_id])
    end

    def sub_task_params
      params[:sub_task].permit(:task_name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :show, :update, :destroy]
  before_action :authenticate_user!
  # skip_before_action :verify_authenticity_token

  def index
    @tasks = Task.where(parent_task_id: nil)
  end

  def new
    @task = current_user.tasks.build
  end

  def edit
  end

  def update
    if @task.update(set_task_params)
      redirect_to @task
    else
      render 'edit'
    end
  end

  def create
    @task = current_user.tasks.build(set_task_params)
    @task.save
    redirect_to @task
    # render plain: params[:task].inspect
  end

  def show
    # render js: "alert('The number is: #{params[:id]}')"
  end

  def destroy
    @task.destroy

    redirect_to tasks_path
  end

  private
    def set_task_params
      params.require(:task).permit(:task_name, :task_type)
    end

    def set_task
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sub_tasks_helper.rb
module SubTasksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todoprac1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class='user-details'>
    <% if !user_signed_in? %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% else %>
      <p> <%= current_user.email %> logged in </p>
      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
    <% end %>
  </div>
  
  <%= yield %>
</body>
</html>

app/views/sub_tasks/_form.html.erb
<%= form_for(@task.sub_tasks.build, as: :sub_task, url: create_sub_task_path, remote: true) do |f| %>
  <%= f.text_field :task_name, placeholder: "Sub Task" %>
  <%= f.submit %>
<% end %>

app/views/sub_tasks/_sub_task.html.erb
<%= sub_task.first.task_name %>

app/views/sub_tasks/create.js.erb
$("#display-sub-tasks").html("<%=j render @task.sub_tasks%>")

app/views/tasks/_form.html.erb
<%= form_for :task, url: tasks_path do |form| %>
  <p>
    <%= form.label :task %><br>
    <%= form.text_area :task_name %>
  </p>

  <p>
    <%= form.label :private_task %><br>
    <%= form.check_box :task_type, {}, true %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_index.html.erb
<% @tasks.each do |task| %>
  <tr>
    <td><%= task.task %></td>
    <td><%= link_to "Edit", edit_task_path(task), remote: true %></td>
  </tr>
<% end %>

app/views/tasks/_task.html.erb
<%= task.task_name %>
<br/>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= form_for :task, url: task_path(@task), method: :patch do |f| %>

  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@task.errors.count, "error") %> prohibited
        this task from being saved:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :task %><br>
    <%= f.text_field :task_name %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>

<table>
  <tr>
    <th>Task</th>
    <th>User</th>
    <th colspan="3"></th>
  </tr>

  <% @tasks.each do |task| %>
    <tr>
      <% if !task.private_task?%>
        <td><%= task.task_name %></td>
        <td><%= task.user.email %></td>
        <td><%= button_to "Show", task_path(task), method: :get%></td>
        <% if current_user == task.user %>
          <td><%= button_to 'Edit', edit_task_path(task), method: :get %></td>
          <td><%= button_to 'Delete', task_path(task),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      <% elsif current_user == task.user %>
        <td><%= task.task_name %></td>
        <td><%= task.user.email %></td>
        <td><%= button_to "Show", task_path(task), method: :get%></td>
        <td><%= button_to 'Edit', edit_task_path(task), method: :get %></td>
        <td><%= button_to 'Delete', task_path(task),
                method: :delete,
                data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br/>
<%= button_to 'New Task', new_task_path, method: :get %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= form_for :task, url: tasks_path do |form| %>
  <p>
    <%= form.label :task %><br>
    <%= form.text_area :task_name %>
  </p>

  <p>
    <%= form.label :private_task %><br>
    <%= form.check_box :task_type, {} , true %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/show.html.erb
<div id="display-task">
  <p>
    <strong>Task:</strong>
    <%= @task.task_name %>
  </p>

<div id="task-wrapper">
  <strong> Sub Tasks </strong> <br/>
  <div id="display-sub-tasks">
    <%= render @task.sub_tasks %><br/>
  </div><br/>
  <div id="sub-task-form">
    <% if current_user == @task.user %>
      <%= render "sub_tasks/form" %>
    <% end %>
  </div>
</div><br/>
</div>
<%= button_to "Back", tasks_path, method: :get%>